FORMAT: 1A
HOST: https://neighbourhoodapi.apiblueprint.org/

# neighbourhood

Neighbourhood is a simple API allowing consumers to:
* Store information about the household members, houses and addresses; 
* Provide the lookup of the house, owners and address;  
* Find people in the neighbourhood according the age groups or household sizes;

## Home Route [/]

### Connection Successful [GET]

+ Response 200 (text/plain)

        You successfully connected to the Neighbourhood API
    
## House Collection [/houses]

### List All Houses [GET]

+ Response 200 (application/json)
            
            [
                 {
                    "id:" 2,
                    "address": "London",
                    "owner": "Harry Potter"
                }
            ]
    

### Create a new House [POST]

+ Request (application/json)

        {
            "address": "London",
            "owner": "Harry Potter"
        }

+ Response 201 (application/json)

    + Headers

            Location: /houses/2

    + Body
            
            {
                "id:" 2,
                "address": "London",
                "owner": "Harry Potter"
            }

    + Schema
    

            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                    "address": "string",
                    "owner": "string"
                }
            }